# Generated by Django 3.2.10 on 2022-06-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentanalyze', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='alpha',
            new_name='alphabet',
        ),
    ]
