# Generated by Django 3.2.10 on 2022-06-17 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentanalyze', '0002_rename_alpha_document_alphabet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Alfavit',
                'verbose_name_plural': 'Alfavit',
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='alphabet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alfavit_to_hujjat', to='contentanalyze.alphabet'),
        ),
    ]
