# Generated by Django 4.1.5 on 2023-01-15 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentanalyze', '0003_auto_20220617_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugatSoha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('nameRus', models.CharField(max_length=100, unique=True)),
                ('nameEng', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Soha',
            },
        ),
        migrations.CreateModel(
            name='Lugat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('kod', models.IntegerField(blank=True, max_length=30, null=True, unique=True)),
                ('wordLatin', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('wordKiril', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('wordRus', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('wordEnglish', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('commentLatin', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('commentKiril', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('commentRus', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('commentEnglish', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('sohaID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soha_to_lugat', to='contentanalyze.soha')),
            ],
            options={
                'verbose_name': 'Lugat',
                'verbose_name_plural': 'Lugatlar',
            },
        ),
    ]
