# Generated by Django 4.1.5 on 2023-01-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentanalyze', '0005_alter_lugat_sohaid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lugatsoha',
            options={'verbose_name': 'lugatSoha'},
        ),
    ]
