# Generated by Django 4.1.5 on 2023-01-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentanalyze', '0007_alter_document_fayl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='miningInfo',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
