# Generated by Django 4.2 on 2023-10-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentanalyze', '0008_alter_document_mininginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('fayl', models.FileField(max_length=250, unique=True, upload_to='')),
                ('author', models.CharField(blank=True, max_length=250, null=True)),
                ('nashr', models.CharField(blank=True, max_length=100, null=True)),
                ('nashrYear', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Manba',
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Muallif', 'verbose_name_plural': 'Mualliflar'},
        ),
        migrations.RemoveField(
            model_name='lugat',
            name='kod',
        ),
        migrations.RemoveField(
            model_name='soha',
            name='resursId',
        ),
        migrations.AlterField(
            model_name='lugat',
            name='sohaID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soha_to_lugat', to='contentanalyze.soha'),
        ),
        migrations.DeleteModel(
            name='Resurs',
        ),
        migrations.AddField(
            model_name='manba',
            name='sohaID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soha_to_manba', to='contentanalyze.soha'),
        ),
    ]
