# Generated by Django 3.1.1 on 2023-10-27 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentanalyze', '0009_manba_alter_author_options_remove_lugat_kod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lugat',
            old_name='sohaID',
            new_name='soha',
        ),
        migrations.RenameField(
            model_name='manba',
            old_name='sohaID',
            new_name='soha',
        ),
        migrations.AddField(
            model_name='lugat',
            name='manba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manba_to_lugat', to='contentanalyze.manba'),
        ),
        migrations.AddField(
            model_name='lugat',
            name='muallif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muallif_to_lugat', to='contentanalyze.author'),
        ),
        migrations.AlterField(
            model_name='alphabet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lugat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lugatsoha',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='manba',
            name='author',
        ),
        migrations.AddField(
            model_name='manba',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, related_name='manba_mualliflari', to='contentanalyze.Author'),
        ),
        migrations.AlterField(
            model_name='manba',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soha',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
